In [61]:
import pandas as pd
tokyo2020 = pd.read_csv('tokyo2020.csv', index_col=False)
del tokyo2020['Unnamed: 0']
tokyo2020[tokyo2020['country'] == 'india']

,country,medalist,sport,event,medal
949,india,CHOPRA NCHOPRA Neeraj,ATH,Men's Javelin Throw,gold
950,india,PUSARLA VSPUSARLA V. Sindhu,BDM,Women's Singles,bronze
951,india,BORGOHAIN LBORGOHAIN Lovlina,BOX,Women's Welter (64-69kg),bronze
952,india,India,HOC,Men,bronze
953,india,MIRABAI CSMIRABAI Chanu Saikhom,WLF,Women's 49kg,silver
954,india,RAVI KRAVI Kumar,WRE,Men's Freestyle 57kg,silver
955,india,BAJRANG BBAJRANG Bajrang,WRE,Men's Freestyle 65kg,bronze

In [6]:
#tokyo2020[tokyo2020['medal'] == "bronze"]
#tokyo2020['event'].str.contains("^\r")
#tokyo2020[tokyo2020['event'].str.match("^\r")]
#tokyo2020['medal'] = tokyo2020['medal'].map({'1': 'gold', '2': 'silver', '3': 'bronze'})
#tokyo2020['event'] = tokyo2020['event'].str.replace('\r','')

,country,medalist,sport,event,medal
5,united-states,BILES SBILES Simone,GAR,Women's Balance Beam,bronze
6,united-states,LEE SLEE Sunisa,GAR,Women's Uneven Bars,bronze
26,united-states,LYLES NLYLES Noah,ATH,Men's 200m,bronze
27,united-states,CHELIMO PCHELIMO Paul,ATH,Men's 5000m,bronze
28,united-states,THOMAS GTHOMAS Gabrielle,ATH,Women's 200m,bronze
...,...,...,...,...,...
1075,ghana,TAKYI STAKYI Samuel,BOX,Men's Feather (52-57kg),bronze
1076,grenada,JAMES KJAMES Kirani,ATH,Men's 400m,bronze
1077,kuwait,ALRASHIDI AALRASHIDI Abdullah,SHO,Skeet Men,bronze
1078,rep-of-moldova,TARNOVSCHI STARNOVSCHI Serghei,CSP,Men's Canoe Single 1000m,bronze
1079,syrian-arab-rep-,ASAAD MASAAD Man,WLF,Men's +109kg,bronze

In [ ]:
#tokyo2020[tokyo2020['medalist'].str.count(" ")>4]

import numpy as np
#t20countries.count().sort_values(['medal'], ascending=True)
#t20countries["medalist"].agg([lambda x: x.count(), lambda x: x.count()])

#categories = {"gold": 3, "silver": 2, "bronze": 1}
#tokyo2020["medal_numeric"] = tokyo2020["medal"].map(categories.get)
#t20countries = tokyo2020.groupby(["country"])
#t20countries["medal_numeric"].agg([lambda x: x.count(), lambda x: x.sum()])

tokyo2020.groupby(["country", "medal"]).count().head(10)

In [ ]:
###tokyo2020 GroupBy countries
def MedalStat(x):
    gold = x[x["medal"] == "gold"]["medal"].count()
    silver = x[x["medal"] == "silver"]["medal"].count()
    bronze = x[x["medal"] == "bronze"]["medal"].count()
    total = gold + silver + bronze
    total_weighted = gold*3 + silver*2 + bronze
    return pd.Series([gold, silver, bronze, total, total_weighted], 
                     index=["Gold", "Silver", "Bronze", "Total", "TotalWeighted"])

expected_df = tokyo2020.groupby(["country"]).apply(MedalStat)

# order by various ways
expected_df.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False).head(60) # By Gold, Silver, Bronze
expected_df.sort_values(['Total'], ascending=False).head(60) # By Total
expected_df.sort_values(['TotalWeighted'], ascending=False).head(60) # By TotalWeighted

In [ ]:
expected_df["rank_Total_min"]=expected_df["Total"].rank(method="min", ascending=False)
expected_df["rank_Total_weighted"]=expected_df["TotalWeighted"].rank(method="min", ascending=False)
expected_df.sort_values(['rank_Total_min'], ascending=True).head(60) # By Total

In [ ]:
#expected_df[abs(expected_df['rank_Total_weighted'] - expected_df['rank_Total_min']) > 10]
# is mexico(004) better or kosovo(200)
#expected_df=expected_df.reset_index()
#del expected_df["index"]
expected_df.to_csv("tokyo2020byCountries.csv")

In [ ]:
import plotly.express as px

fig = px.bar(expected_df.sort_values(['Total'], ascending=False), x='country', y="Total")
fig.show()
fig = px.bar(expected_df.sort_values(['Total'], ascending=False), x='country', y=["Gold", "Silver", "Bronze"])
fig.show()